version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm install -g @openai/codex
      - npm install -g @elephant-xyz/mcp
      - echo "Node.js runtime set to version 22."
  pre_build:
    commands:
      - set -euo pipefail
      - export RUNTIME_DOWNLOAD_DIR="/tmp/runtime-archives"
      - export RUNTIME_WORK_DIR="/tmp/runtime-workdir"
      - mkdir -p "${RUNTIME_DOWNLOAD_DIR}" "${RUNTIME_WORK_DIR}"
      - >
        if [[ -z "${RUNTIME_ARTIFACTS_BUCKET:-}" ]]; then
          echo "RUNTIME_ARTIFACTS_BUCKET environment variable is required." >&2
          exit 1
        fi
      - >
        S3_SOURCE="s3://${RUNTIME_ARTIFACTS_BUCKET}"
      - >
        if [[ -n "${RUNTIME_ARTIFACTS_PREFIX:-}" ]]; then
          S3_SOURCE="${S3_SOURCE%/}/${RUNTIME_ARTIFACTS_PREFIX}"
        fi
      - aws s3 cp "${S3_SOURCE}" "${RUNTIME_DOWNLOAD_DIR}" --recursive --exclude "*" --include "*.zip"
      - >
        if ! compgen -G "${RUNTIME_DOWNLOAD_DIR}/*.zip" > /dev/null; then
          echo "No runtime zip archives found at ${S3_SOURCE}" >&2
          exit 1
        fi
      - |
        for archive in "${RUNTIME_DOWNLOAD_DIR}"/*.zip; do
          echo "Unpacking ${archive}..."
          unzip -qo "${archive}" -d "${RUNTIME_WORK_DIR}"
        done
  build:
    commands:
      - cd "${RUNTIME_WORK_DIR}"
      - >
        if [[ -z "${RUNTIME_ENTRYPOINT:-}" ]]; then
          echo "RUNTIME_ENTRYPOINT environment variable is required." >&2
          exit 1
        fi
      - >
        if [[ ! -f "${RUNTIME_ENTRYPOINT}" ]]; then
          echo "Entry point ${RUNTIME_ENTRYPOINT} not found after extraction." >&2
          exit 1
        fi
      - node "${RUNTIME_ENTRYPOINT}"
