AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM template for processing EventBridge WorkflowEvent events with TypeScript Lambda

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: MWAAEnvironment

Globals:
  Function:
    Timeout: 60
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON

Resources:
  WorkflowEventHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${EnvironmentName}-workflow-event-handler"
      Runtime: nodejs22.x
      Architectures:
        - arm64
      Handler: index.handler
      CodeUri: lambdas/event-handler
      Description: "Processes EventBridge WorkflowEvent events from elephant.workflow source"
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        WorkflowEventRule:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - elephant.workflow
              detail-type:
                - WorkflowEvent
            State: ENABLED
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        EntryPoints:
          - index.ts
        Sourcemap: true
        LogLevel: info

Outputs:
  WorkflowEventHandlerFunctionName:
    Description: Name of the workflow event handler Lambda function
    Value: !Ref WorkflowEventHandlerFunction
  WorkflowEventHandlerFunctionArn:
    Description: ARN of the workflow event handler Lambda function
    Value: !GetAtt WorkflowEventHandlerFunction.Arn
  WorkflowEventRuleName:
    Description: Name of the EventBridge rule that triggers the Lambda
    Value: !Sub "${EnvironmentName}-workflow-event-rule"
