.PHONY: build-WorkflowSharedLayer

build-WorkflowSharedLayer:
	mkdir -p "$(ARTIFACTS_DIR)/nodejs/node_modules/shared"
	cp src/*.mjs "$(ARTIFACTS_DIR)/nodejs/node_modules/shared/"
	cp src/package.json "$(ARTIFACTS_DIR)/nodejs/node_modules/shared/"
